<a href="https://colab.research.google.com/github/HaniePoursina/NLP/blob/main/first_practice_of_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense
from keras.preprocessing.sequence import pad_sequences 
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
# Define 10 restaurant reviews
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
#Define labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [13]:
Vocab_size = 50
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[8, 28, 29], [49, 40], [27, 45], [32, 42], [49, 42], [5], [5, 26], [2], [6, 22], [2, 46, 30, 32]]


In [16]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[ 8 28 29  0]
 [49 40  0  0]
 [27 45  0  0]
 [32 42  0  0]
 [49 42  0  0]
 [ 5  0  0  0]
 [ 5 26  0  0]
 [ 2  0  0  0]
 [ 6 22  0  0]
 [ 2 46 30 32]]


In [23]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten_5 (Flatten)         (None, 32)                0         
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(padded_reviews,labels,epochs=100,verbose=0)

In [24]:
print(embedding_layer.get_weights()[0].shape)

(50, 8)
